lib/rex/text/unicode.rb

During the research problems with SMB authorization using login with national symbols (Russian) I saw in tcpdump, that the convert to UTF-16LE is not correct.
```ruby
2.2.3 :001 > "АДМИНИСТРАТОР".unpack('C*').pack('v*').unpack("H*") == "АДМИНИСТРАТОР".encode('utf-16le').unpack("H*")
=> false
2.2.3 :002 > "АДМИНИСТРАТОР".unpack('U*').pack('v*').unpack("H*") == "АДМИНИСТРАТОР".encode('utf-16le').unpack("H*")
=> true
```

Fix unicode conversion for SMB Logins

---

lib/rex/text/hex.rb

This PR changes the behavior of the data sanitization function that converts bad ANSI chars into hex values.  Predictably, it goes south quick when presented with UTF-8.
This sanitization did not target characters associated with SQL injection or other attacks, only chars 0x00-0x20 and above 0x80.... so there appears to be no security motive, just preventing any non-printable ANSI characters from entering the database.

Stop ascii_safe_hex() from crashing on UTF-8 strings

---

lib/rex/text/table.rb

This resolves issue [#7500](https://github.com/rapid7/metasploit-framework/issues/7500) in `metasploit-framework`.
As suggested on that thread, all text is converted to UTF-8 on entering the `pad` function. A check on the encoding ensures graceful exit if an unexpected encoding (like UTF-16 or UTF-32) is encountered.

Fix padding for Unicode strings

---

lib/rex/text/unicode.rb

This delta was generated from the SVIT fork's version of rex/text.
Git blame shows this diff to be part of 0e3b1585 on 20130430.
Other changes have been omitted as they do not pertain to upstream
imports of the fork's functional changes.
Commit message indicates this to be part of the Powershell cleanup
effort during one of the merges upstream, and designed to deal with
parsing foreign PSH scripts containing aberrant characters.
---
This implementation alters a root namespace, using a const_set method, which isn't ideal. Does it make sense to implement the method as a local extension of the namespace within Rex::Text, or dynamically alter the execution context in ::Unicode at runtime from blocks which deal with strange characters?

Import ::Unicode.const_missing to rex/text/unicode

---

lib/rex/text.rb
lib/rex/text/pattern.rb

Some code in `pattern_create()` smells dead to me, and in testing I couldn't get it to light up. If we're concerned about performance of generating huge patterns, it might be better to `converge_sets()` only once and cycle its output. I can try my hand at that if it's decided to be useful.

Remove dead code, fix typo

---

lib/rex/text/table.rb

This arose from this issue: https://github.com/rapid7/metasploit-framework/issues/7988
This only happens when IPs are passed in as String objects and one is IPv4 and the other is IPv6. Not sure this is the most elegant fix, but for the frequency with which this will ever happen, it might be good enough.

handle comparing ipv4 and ipv6

---

lib/rex/text/lang.rb

Avoids errors in Visual Basic for Applications. Closes https://github.com/rapid7/metasploit-framework/issues/8147. 
More background:
https://msdn.microsoft.com/en-us/library/office/gg264236.aspx
The VBA format limits line continuations to 25. There are a few methods that can be used: http://stackoverflow.com/questions/2806151/excel-macros-too-many-line-continuations
This is the hackiest solution that actually works. Really long payloads will need a better fix (one of the ones from Stack Overflow would do nicely), but 80 bytes fits windows/meterpreter/reverse_https in only nine lines out of a maximum of 25.

Update lang.rb: Allow longer VBA lines

---

lib/rex/text/block_api.rb

Seems that "fun" is a keyword which the RBX compiler does not like.
Change block_api.rb to use "func" instead.
Addresses:
```
main # Rubinius::Loader at core/loader.rb:861
script # Rubinius::Loader at core/loader.rb:679
load_script . Rubinius::CodeLoader at core/code_loader.rb:590
load_script # Rubinius::CodeLoader at core/code_loader.rb:505
__script__ # Object at msfconsole:49
require # Kernel(Object) at core/kernel.rb:851
require . Rubinius::CodeLoader at core/code_loader.rb:233
__script__ # Object at lib/msf/core/payload_generator.rb:2
require # Kernel(Object) at core/kernel.rb:851
require . Rubinius::CodeLoader at core/code_loader.rb:233
__script__ # Object at lib/msf/core/payload/apk.rb:3
require # Kernel(Object) at core/kernel.rb:851
require . Rubinius::CodeLoader at …
```

Rubinius compiler does not like fun

---

lib/rex/text/randomize.rb

The #shuffle! method uses the Fisher-Yates algorithm.
I think this will do the job just as well, if not better?
Same benchmark I shared in https://github.com/rapid7/rex-text/pull/15
```ruby
require "benchmark/ips"
def fast
arr = [*1..100]
arr.shuffle! 
end
def slow
arr = [*1..100]
len = arr.length
max = len - 1
cyc = [* (0..max) ]
for d in cyc
e = rand(d+1)
next if e == d
f = arr[d];
g = arr[e];
arr[d] = g;
arr[e] = f;
end
return arr
end
Benchmark.ips do |x|
x.report("slower") { slow }
x.report("faster") { fast }
x.compare!
end
```
```
Warming up --------------------------------------
slower     2.457k i/100ms
faster    13.637k i/100ms
Calculating -------------------------------------
slower     25.076k (± 4.9%) i/s -    125.307k in   5.009132s
faster    160.511k (± 4.1%) i/s - …
```

simplify shuffle_a implementation

---

lib/rex/text/randomize.rb

By removing regex and utilizing maps to limit unnecessary allocation allows for some performance gains for the [`to_mixed_case_array` ](https://github.com/rapid7/rex-text/blob/master/lib/rex/text/randomize.rb#L37) method.
```ruby
require "benchmark/ips"
def fast
str = "abc1"
letters = str.each_char.map { |l| [l.downcase, l.upcase] }
(1 << str.size).times.map do |i| 
this_str = ""
("%0#{str.size}b" % i).each_char.map(&:to_i).each_with_index do |d,i|
this_str << letters[i][d]
end
this_str
end.uniq
end
def slow
str = "abc1"
letters = []
str.scan(/./).each { |l| letters << [l.downcase, l.upcase] }
coords = []
(1 << str.size).times { |i| coords << ("%0#{str.size}b" % i) }
mixed = []
coords.each do |coord|
c = coord.scan(/./).map {|x| x.to_i}
this_str = ""
c.each_with_index { |d,i| this_str << …
```

speedup to_mixed_case_array method

---

lib/rex/text/binary_manipulation.rb

Instead of using type regular expressions and a map to reject out the words we don’t want, we can just as easily use one regular expression yielding a 5x speed bump in my benchmarks.
```ruby
require "benchmark/ips"
def fast
str = "Ain't no party like a scranton party, cuz a scranton party don't stop! "
strict = true
return str.split(/\b/) unless strict
str.scan(/\w+/)
end
def slow
str = "Ain't no party like a scranton party, cuz a scranton party don't stop! "
strict = true
splits = str.split( /\b/ )
splits.reject! { |w| !(w =~ /\w/) } if strict                                                             
splits
end
puts fast == slow
Benchmark.ips do |x|
x.report("slower") { slow }
x.report("faster") { fast }
x.compare!
end
```
```
true
Warming up -------------------------------------- …
```

use single regular expression for strict case

---

lib/rex/text/base64.rb

Using the strip method gives the same result and is up to 5x faster in my benchmarks. This also simplifies the base64 encoding API ( removing the delim argument ):
```ruby
require "benchmark/ips"
require "pry"
def fast
str = "I love Ruby programming!"
[str.to_s].pack("m").strip
end
def slow
str = "I love Ruby programming!"
delim = ""
[str.to_s].pack("m").gsub(/\s+/, delim)
end
puts fast == slow
Benchmark.ips do |x|
x.report("slower") { slow }
x.report("faster") { fast }
x.compare!
end
```
```
true
Warming up --------------------------------------
slower    22.861k i/100ms
faster    92.001k i/100ms
Calculating -------------------------------------
slower    261.858k (± 3.7%) i/s -      1.326M in   5.070992s
faster      1.291M (± 4.5%) i/s -      6.532M in   5.068937s
Comparison:
faster: …
```

remove unnecessary gsub regex to remove newline

---

lib/rex/text/xor.rb
spec/rex/text/xor_spec.rb

This removes support for integer strings, which don't work well with variable-length key strings.
```
[1] pry(#<Msf::Framework>)> Rex::Text.xor(0x0f, 'hello world')
=> "gjcc`/x`}ck"
[2] pry(#<Msf::Framework>)> Rex::Text.to_hex(Rex::Text.xor('0x0f', 'hello world'), '')
=> "581d5c0a5f584709421454"
[3] pry(#<Msf::Framework>)> Rex::Text.xor("\x00\x00\x00\x00\x00\x0c", 'hello world')
=> "hello,world"
[4] pry(#<Msf::Framework>)>
```
```
wvu@kharak:~$ xortool-xor -h 0f -s "hello world"
gjcc`/x`}ck
wvu@kharak:~$ xortool-xor -r 0x0f -s "hello world" | tr -d "\n" | xxd -p
581d5c5f584709421454
wvu@kharak:~$ xortool-xor -s "\x00\x00\x00\x00\x00\x0c" -s "hello world"
hello,world
wvu@kharak:~$
```

Implement XOR with variable-length key

---

lib/rex/text/lang.rb

Just a tiny fix to make the python formatted payload work for both python2 and python3.
By default python3 uses unicode strings, so by adding the `b` prefix it will interpret the string as raw bytes.

fix python3 bytes string

---

lib/rex/text/color.rb

An alternate fix for https://github.com/rapid7/metasploit-framework/pull/13489
Verification
=========

Set prompt escape chars only when they work

---

Gemfile
lib/rex/text.rb
lib/rex/text/wrapped_table.rb
spec/rex/text/wrapped_table_spec.rb
spec/spec_helper.rb

Add initial support for word wrapping rex tables.  Functionality currently missing from this initial work:
- Correct calculation of southeast asian characters 
- Color code support
- Specifying specific columns to not be wordwrapped
- Smarter splitting of words, each cell is naively split into the required column width
- Handling SIGWINCH
```
msf5 > info post/windows/gather/phish_windows_credentials 
...
Provided by:
Wesley Neelen <security@forsec.nl>
Matt Nelson
Compatible session types:
Meterpreter
Basic options:
Name         Current Setting                                                                Required  Description
----         ---------------                                                                --------  -----------
DESCRIPTION  {PROCESS_NAME} needs your permissions …
```

Add initial support for word wrapping rex tables

---

lib/rex/text/table.rb

This fixes a stack trace where if `IO.console` is nil, the WrappedTable will fail to generate leading to stacktraces instead of output within `msfconsole`. I came across this when debugging Metasploit with RubyMine and running the `jobs` command. The proposed solution is to check if `::IO.console` is nil before wrapping tables based on its width. If the width isn't available from the console, then there's probably no point in automatically wrapping tables.
Example stack trace:
```
msf6 exploit(windows/smb/psexec) > jobs
[-] Error while running command jobs: undefined method `winsize' for nil:NilClass
Call stack:
/home/smcintyre/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/rex-text-0.2.28/lib/rex/text/wrapped_table.rb:74:in `initialize' …
```

Also check the IO.console is not nil before wrapping based on its width

---

lib/rex/text/table.rb

Reverts rapid7/rex-text#34
Looks like this change breaks in Jenkins CI, reverting for now :+1:

Revert "Also check the IO.console is not nil before wrapping based on its width"

---

lib/rex/text/wrapped_table.rb
spec/rex/text/wrapped_table_spec.rb
spec/spec_helper.rb

Alternative implementation to https://github.com/rapid7/rex-text/pull/34

Default console width when api is unavailable

---

lib/rex/text/table.rb
spec/rex/text/table_spec.rb
spec/rex/text/wrapped_table_spec.rb

Let's update the API to allow opting out of wrapped tables on a per table basis with the option:
```
'WordWrap'   => false,
```

Allow per table configuration of wrapped tables

---

lib/rex/text/rand.rb

Fix #12110
Adds rand_password method which can be used to generate password of desired length and custom attributes for uppercase, lowercase, numbers and special characters.
This PR was created in response to issue [#12110](https://github.com/rapid7/metasploit-framework/issues/12110) on Metasploit-Framework.

 Add rand_password method to Rex::Text

---

lib/rex/text/lang.rb

There seems to be a problem with vbapplication payload generation. The loop starts at 1, so the first byte is lost. This fix resolves this issue.

Fix for vbapplication payload generation

---

lib/rex/text/rand.rb

Create random function name generator by combining common verbs
and subjects seen in import/export tables, and sprinkling in some
random capitalization for entropy.
Testing:
Local only via IRB -
```
>> Rex::Text.rand_func_name
=> "Releaseaddress"
>> Rex::Text.rand_func_name
=> "FreeUser"
>> Rex::Text.rand_func_name
=> "Releasefile"
>> Rex::Text.rand_func_name
=> "Describeaddress"
```

Implement Rex::Text random function name generator

---

lib/rex/text/wrapped_table.rb
spec/rex/text/wrapped_table_spec.rb

Fixes a crash replicated by https://github.com/rapid7/metasploit-framework/pull/16598#discussion_r904237970
Note - If the string provided isn't in the right encoding, there's a potential the rendered text will be invalid - but at least it will no longer crash.
Related issues:
https://github.com/rapid7/metasploit-framework/issues/15833
https://github.com/rapid7/metasploit-framework/issues/14955
https://github.com/rapid7/metasploit-framework/issues/15044
As well a comment from bcoles with additional context https://github.com/rapid7/metasploit-framework/issues/15833#issuecomment-1023993469

Fix rex text split string crash

---

lib/rex/text/lang.rb

Added `self.to_golang` and `self.to_golang_comment` for golang buffer arary output format.
There is an option when declaring a golang array to define the array size `buf := [3]byte{0x00,0x00,0x00}`, but I found that letting golang dynamically define the array size is a better approach.
The aim is to allow golang buffer output when generating the msfvenom payload using `msfvenom -p windows/x64/exec CMD=calc.exe -f go` 
Returning this format:
```
/*
windows/exec - 193 bytes
https://metasploit.com/
VERBOSE=false, PrependMigrate=false, EXITFUNC=process, CMD=calc.exe
*/
buf := []byte{0xfc, 0xe8, 0x82, 0x00, 0x00, 0x00, 0x60, 0x89, 0xe5, 0x31, 0xc0, 0x64, 0x8b, 0x50, 0x30, 0x8b, 0x52, 0x0c, 0x8b, 0x52, 0x14, 0x8b, 0x72, 0x28, 0x0f, 0xb7, 0x4a, 0x26, 0x31, 0xff, 0xac, 0x3c, 0x61, 0x7c, 0x02, …
```

added golang support for output.

---

lib/rex/text/hex.rb
lib/rex/text/lang.rb
spec/rex/text/hex_spec.rb
spec/rex/text/lang_spec.rb

I suggest reviewing the code without whitespace changes. I converted some tab characters to spaces.
This fixes #51. The `#hexify` and `#to_$lang` methods were not correctly wrapping at the specified number of columns. This also adds a unit test to show that the wrapping is working now, and to ensure that it continues to work as expected in the future.
```
[10] pry(main)> puts Rex::Text.to_ruby("A"*50, 60)
buf = 
"\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41" +
"\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41" +
"\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41" +
"\x41\x41\x41\x41\x41\x41\x41\x41"
=> nil
[11] pry(main)> puts Rex::Text.to_python("A"*50, 60)
buf =  b""
buf += b"\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41\x41"
buf += …
```

Fix Language Wrapping

---

lib/rex/text.rb
lib/rex/text/color.rb
lib/rex/text/wrapped_table.rb
spec/rex/text/table_spec.rb
spec/rex/text/wrapped_table_spec.rb
spec/rex/text_spec.rb
spec/support/matchers/have_maximum_display_width.rb

This PR adds color support for wrapped tables, as well as tests to cover as many edge cases as possible.
Checkout this branch and add the `rex-text` gem into your Metasploit `gemfile`.
```Ruby
gemspec name: 'metasploit-framework'
gem "rex-text", path: "../rex-text"
```
Set [WordWrap](https://github.com/rapid7/metasploit-framework/blob/5d935bdd0a25ff20d01f67e3c822685fc1c79aee/lib/msf/ui/console/command_dispatcher/modules.rb#L16) to `true` within `lib/msf/ui/console/command_dispatcher/modules.rb`
List the steps needed to make sure this thing works

Adds color support for wrapped tables

---

lib/rex/text/lang.rb
spec/rex/text/lang_spec.rb

This PR adds support for Rust shellcode generation which supports both rust and rustlang formats. Please note that an [unmutable u8 array](https://doc.rust-lang.org/std/primitive.array.html) is created by default.
Example msfvenom Rust shellcode for calc.exe:
Example msfconsole Rust shellcode for calc.exe:
This has been tested with my own [Rust basic shellcode injector](https://github.com/memN0ps/arsenal-rs/tree/main/shellcode_runner_classic-rs)

Adding support for Rust formatted shellcode generation

---

lib/rex/text.rb
lib/rex/text/wrapped_table.rb
spec/rex/text/wrapped_table_spec.rb

The commit for this PR are actually changes @adfoster-r7 made. We didn't want to open a new PR and loose the paper trail here with comments/recommendations, so we just translated those changes to this PR. Thanks Alan 🎉 
This PR adds support to remove column headers and column decoration from wrapped tables via Stylers.
This is to support a Metasploit Framework [PR](https://github.com/rapid7/metasploit-framework/pull/16946) to add row indicators to `show targets` command. 
Users can now pass specific columns Stylers.
```Ruby
'ColProps' => {
'IsTarget' => {
'Stylers' => [Msf::Ui::Console::TablePrint::RowIndicatorStyler.new],
'ColumnStylers' => [Msf::Ui::Console::TablePrint::OmitColumnHeader.new],
'Width' => 2
}
}
```
When it was being calculated it was using the column header length from …

Adds support to remove column decoration and headers

---

lib/rex/text/wrapped_table.rb
spec/rex/text/wrapped_table_spec.rb

… passwords
Fixes [Metasploit issue 17714](https://github.com/rapid7/metasploit-framework/issues/17714) where the service command is not sorting the rows when it is getting saved into a csv file.
Add some services before to test this.
Here is the sample of the output for the above command before fix.
```
msf6 > services -u -O 1 -o output.csv
[*] Wrote services to ~/git/metasploit-framework/output.csv
msf6 >
```
File output
```
cat ~/git/metasploit-framework/output.csv
host,port,proto,name,state,info
"147.124.211.125","80","tcp","http","open",""
"66.33.214.230","443","tcp","http","open",""
```
After the fix.
Here is the sample output for above data
```
msf6 > services -u -O 1 -o output.csv
[*] Wrote services to ~/git/metasploit-framework/output.csv
msf6 >
```
File Output.
```
cat …
```

metasploit services sorting issue when saved into csv file

---

lib/rex/text/table.rb
lib/rex/text/wrapped_table.rb
spec/rex/text/table_spec.rb
spec/rex/text/wrapped_table_spec.rb

Update rex-text to support disabling whitespace stripping by default

Allow opting out of whitespace removal

---

.github/workflows/verify.yml

This PR upversions the github actions, from `actions/checkout@v2` to `actions/checkout@v4`.
v2 ran on Node.js 16, which is deprecated by Github. Runs using v2 have a deprecation warning, as can be viewed at the bottom of https://github.com/rapid7/rex-text/actions/runs/8460297168 
v4 runs on Node.js 20, which clears these deprecation warnings.
More information on this can be found at https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Upversion Github actions 

---

lib/rex/text/wrapped_table.rb
spec/rex/text/wrapped_table_spec.rb

Best reviewed width [whitespace ignored](https://github.com/rapid7/rex-text/pull/71/files?w=1)
Update rex-text table width calculation to default to INFINITY if the console is calculated to be 0 columns wide, which can be the the case when running under docker

Default 0 console width to infinity
